language: generic
sudo: required

services:
  - docker

install:
  # Install snapd.
  - sudo apt install snapd

script:
  # Build the snap!
  - docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c
      "apt update -qq && cd $(pwd) &&
      snapcraft"
  # Install it.
  - sudo snap install hello_0.1_amd64.snap --dangerous
  # Run 'hello'
  - hello