language: generic
sudo: required

install:
  # Install snapcraft.
  - sudo apt-add-repository -y ppa:snappy-dev/tools
  - sudo apt-get update
  - sudo apt-get -y install snappy-tools snapcraft

script:
  # Build the snap!
  - snapcraft
  # Install it.
  - sudo snap install hello_0.1_amd64.snap --dangerous
  # Run 'hello'
  - hello